name: weather_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

  geolocator: ^13.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


    # fonts:
    #  - family: flutterfonts
    #   fonts:
    #    - asset: assets/fonts/flutterfonts.ttf
